name: Run Test using Docker Image
on:
  workflow_dispatch:
jobs:
  run_web:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Pull Docker Image
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/playwright-demo:latest
          options: -v ${{ github.workspace }}:/app
      -
        name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ${{ github.workspace }}/playwright-report/
          retention-days: 7